[2024-10-14T17:39:09.949+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T17:39:10.066+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-14T17:39:10.163+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-14T17:39:10.171+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-14T17:39:10.384+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ccl_to_redshift> on 2024-10-09 00:00:00+00:00
[2024-10-14T17:39:10.469+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=19233) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T17:39:10.484+0000] {standard_task_runner.py:72} INFO - Started process 19257 to run task
[2024-10-14T17:39:10.520+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_ccl', 'ccl_to_redshift', 'scheduled__2024-10-09T00:00:00+00:00', '--job-id', '304', '--raw', '--subdir', 'DAGS_FOLDER/dag_ccl.py', '--cfg-path', '/tmp/tmp4xoi4pqg']
[2024-10-14T17:39:10.573+0000] {standard_task_runner.py:105} INFO - Job 304: Subtask ccl_to_redshift
[2024-10-14T17:39:12.844+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-10-09T00:00:00+00:00 [running]> on host f03003374728
[2024-10-14T17:39:39.954+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ccl' AIRFLOW_CTX_TASK_ID='ccl_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-09T00:00:00+00:00'
[2024-10-14T17:39:39.984+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T17:39:40.129+0000] {logging_mixin.py:190} INFO - 2024-10-10
[2024-10-14T17:39:41.804+0000] {logging_mixin.py:190} INFO -             0          1
0       fecha  DOLAR CCL
1  10/10/2024    1177.07
[2024-10-14T17:39:42.076+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-14T17:39:42.078+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-14T17:39:44.225+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ccl_to_redshift.py", line 12, in ccl_to_redshift
    load_data_to_redshift(df, table_name)
  File "/opt/airflow/dags/load_data_to_redshift.py", line 24, in load_data_to_redshift
    psycopg2.extras.execute_values(cur, query, data)
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "0" of relation "dolar_ccl" does not exist

[2024-10-14T17:39:44.795+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_ccl, task_id=ccl_to_redshift, run_id=scheduled__2024-10-09T00:00:00+00:00, execution_date=20241009T000000, start_date=20241014T173910, end_date=20241014T173944
[2024-10-14T17:39:45.716+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T17:39:45.995+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 304 for task ccl_to_redshift (column "0" of relation "dolar_ccl" does not exist
; 19257)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ccl_to_redshift.py", line 12, in ccl_to_redshift
    load_data_to_redshift(df, table_name)
  File "/opt/airflow/dags/load_data_to_redshift.py", line 24, in load_data_to_redshift
    psycopg2.extras.execute_values(cur, query, data)
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "0" of relation "dolar_ccl" does not exist

[2024-10-14T17:39:47.677+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-14T17:39:48.379+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T17:39:48.385+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-14T17:58:20.937+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T17:58:20.967+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-14T17:58:20.981+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-14T17:58:20.982+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-14T17:58:21.001+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ccl_to_redshift> on 2024-10-09 00:00:00+00:00
[2024-10-14T17:58:21.011+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=19516) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T17:58:21.014+0000] {standard_task_runner.py:72} INFO - Started process 19529 to run task
[2024-10-14T17:58:21.013+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_ccl', 'ccl_to_redshift', 'scheduled__2024-10-09T00:00:00+00:00', '--job-id', '314', '--raw', '--subdir', 'DAGS_FOLDER/dag_ccl.py', '--cfg-path', '/tmp/tmpexey29r8']
[2024-10-14T17:58:21.019+0000] {standard_task_runner.py:105} INFO - Job 314: Subtask ccl_to_redshift
[2024-10-14T17:58:21.176+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-10-09T00:00:00+00:00 [running]> on host f03003374728
[2024-10-14T17:58:21.858+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ccl' AIRFLOW_CTX_TASK_ID='ccl_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-09T00:00:00+00:00'
[2024-10-14T17:58:21.864+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T17:58:21.885+0000] {logging_mixin.py:190} INFO - 2024-10-09
[2024-10-14T17:58:22.311+0000] {logging_mixin.py:190} INFO - 0       fecha dolar_ccl
1  2024-10-09   1191.42
[2024-10-14T17:58:22.318+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-14T17:58:22.319+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-14T17:58:24.335+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-14T17:58:24.342+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T17:58:24.342+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_ccl, task_id=ccl_to_redshift, run_id=scheduled__2024-10-09T00:00:00+00:00, execution_date=20241009T000000, start_date=20241014T175820, end_date=20241014T175824
[2024-10-14T17:58:24.390+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-14T17:58:24.406+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T17:58:24.408+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-16T14:41:38.090+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-16T14:41:38.127+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-16T14:41:38.151+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-16T14:41:38.153+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-16T14:41:38.200+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ccl_to_redshift> on 2024-10-09 00:00:00+00:00
[2024-10-16T14:41:38.212+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=287) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-16T14:41:38.215+0000] {standard_task_runner.py:72} INFO - Started process 310 to run task
[2024-10-16T14:41:38.225+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_ccl', 'ccl_to_redshift', 'scheduled__2024-10-09T00:00:00+00:00', '--job-id', '413', '--raw', '--subdir', 'DAGS_FOLDER/dag_ccl.py', '--cfg-path', '/tmp/tmpvmfsw6ur']
[2024-10-16T14:41:38.254+0000] {standard_task_runner.py:105} INFO - Job 413: Subtask ccl_to_redshift
[2024-10-16T14:41:38.341+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-10-09T00:00:00+00:00 [running]> on host f03003374728
[2024-10-16T14:41:38.786+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ccl' AIRFLOW_CTX_TASK_ID='ccl_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-09T00:00:00+00:00'
[2024-10-16T14:41:38.788+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-16T14:41:38.802+0000] {logging_mixin.py:190} INFO - 2024-10-09
[2024-10-16T14:41:39.206+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-16T14:41:39.208+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-16T14:41:41.191+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-16T14:41:41.202+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-16T14:41:41.202+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_ccl, task_id=ccl_to_redshift, run_id=scheduled__2024-10-09T00:00:00+00:00, execution_date=20241009T000000, start_date=20241016T144138, end_date=20241016T144141
[2024-10-16T14:41:41.241+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-16T14:41:41.280+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-16T14:41:41.284+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
