[2024-10-14T17:32:42.830+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T17:32:57.143+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-15T00:00:00+00:00 [queued]>
[2024-10-14T17:33:00.927+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-15T00:00:00+00:00 [queued]>
[2024-10-14T17:33:01.047+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-14T17:33:04.140+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ccl_to_redshift> on 2024-09-15 00:00:00+00:00
[2024-10-14T17:33:06.331+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=19111) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T17:33:06.647+0000] {standard_task_runner.py:72} INFO - Started process 19172 to run task
[2024-10-14T17:33:07.899+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_ccl', 'ccl_to_redshift', 'scheduled__2024-09-15T00:00:00+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/dag_ccl.py', '--cfg-path', '/tmp/tmpxlnsagoe']
[2024-10-14T17:33:08.128+0000] {standard_task_runner.py:105} INFO - Job 300: Subtask ccl_to_redshift
[2024-10-14T17:33:13.603+0000] {job.py:229} INFO - Heartbeat recovered after 58.17 seconds
[2024-10-14T17:33:21.010+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-15T00:00:00+00:00 [running]> on host f03003374728
[2024-10-14T17:33:24.703+0000] {job.py:229} INFO - Heartbeat recovered after 10.97 seconds
[2024-10-14T17:33:42.360+0000] {job.py:229} INFO - Heartbeat recovered after 19.10 seconds
[2024-10-14T17:33:51.635+0000] {job.py:229} INFO - Heartbeat recovered after 10.57 seconds
[2024-10-14T17:34:02.736+0000] {job.py:229} INFO - Heartbeat recovered after 11.37 seconds
[2024-10-14T17:34:31.337+0000] {job.py:229} INFO - Heartbeat recovered after 11.34 seconds
[2024-10-14T17:35:08.367+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ccl' AIRFLOW_CTX_TASK_ID='ccl_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-09-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-15T00:00:00+00:00'
[2024-10-14T17:35:08.736+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T17:35:10.123+0000] {logging_mixin.py:190} INFO - 2024-09-16
[2024-10-14T17:35:18.601+0000] {logging_mixin.py:190} INFO -             0          1
0       fecha  DOLAR CCL
1  16/09/2024    1240.97
[2024-10-14T17:35:20.326+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-14T17:35:20.454+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-14T17:35:23.349+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ccl_to_redshift.py", line 12, in ccl_to_redshift
    load_data_to_redshift(df, table_name)
  File "/opt/airflow/dags/load_data_to_redshift.py", line 20, in load_data_to_redshift
    cols = ",".join([f'"{col}"' for col in df.columns])
                                           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'columns'
[2024-10-14T17:35:25.321+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_ccl, task_id=ccl_to_redshift, run_id=scheduled__2024-09-15T00:00:00+00:00, execution_date=20240915T000000, start_date=20241014T173258, end_date=20241014T173525
[2024-10-14T17:35:27.137+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T17:35:27.463+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 300 for task ccl_to_redshift ('NoneType' object has no attribute 'columns'; 19172)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ccl_to_redshift.py", line 12, in ccl_to_redshift
    load_data_to_redshift(df, table_name)
  File "/opt/airflow/dags/load_data_to_redshift.py", line 20, in load_data_to_redshift
    cols = ",".join([f'"{col}"' for col in df.columns])
                                           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'columns'
[2024-10-14T17:35:28.518+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-14T17:35:30.611+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-10-14T17:35:30.990+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T17:35:31.267+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-16T14:41:14.196+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-16T14:41:14.291+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-15T00:00:00+00:00 [queued]>
[2024-10-16T14:41:14.335+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-15T00:00:00+00:00 [queued]>
[2024-10-16T14:41:14.340+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-16T14:41:14.640+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ccl_to_redshift> on 2024-09-15 00:00:00+00:00
[2024-10-16T14:41:14.684+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=184) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-16T14:41:14.702+0000] {standard_task_runner.py:72} INFO - Started process 202 to run task
[2024-10-16T14:41:14.709+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_ccl', 'ccl_to_redshift', 'scheduled__2024-09-15T00:00:00+00:00', '--job-id', '389', '--raw', '--subdir', 'DAGS_FOLDER/dag_ccl.py', '--cfg-path', '/tmp/tmp5fo9oq4p']
[2024-10-16T14:41:14.714+0000] {standard_task_runner.py:105} INFO - Job 389: Subtask ccl_to_redshift
[2024-10-16T14:41:14.829+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-15T00:00:00+00:00 [running]> on host f03003374728
[2024-10-16T14:41:15.311+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ccl' AIRFLOW_CTX_TASK_ID='ccl_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-09-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-15T00:00:00+00:00'
[2024-10-16T14:41:15.312+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-16T14:41:15.328+0000] {logging_mixin.py:190} INFO - 2024-09-15
[2024-10-16T14:41:17.421+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-16T14:41:17.422+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-16T14:41:18.683+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-16T14:41:18.693+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-16T14:41:18.694+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_ccl, task_id=ccl_to_redshift, run_id=scheduled__2024-09-15T00:00:00+00:00, execution_date=20240915T000000, start_date=20241016T144114, end_date=20241016T144118
[2024-10-16T14:41:18.751+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-16T14:41:18.772+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-16T14:41:18.773+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
